name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
    - run: dotnet build --configuration Release
    - run: zip -r ${{ github.event.repository.name }}_${{ steps.date.outputs.date }}.zip bin/Release
    - uses: softprops/action-gh-release@v2
      with:
        draft: true
        generate_release_notes: true
        files: ${{ github.event.repository.name }}_${{ steps.date.outputs.date }}.zip
        tag_name: ${{ steps.date.outputs.date }}
